- hosts: servers

  vars:
    nginx_port: 80
    root_dir: /var/tmp/www
    invite: "This is server {{ ansible_hostname}}!"

  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: 
          - nginx
          - cowsay
        state: present
        update_cache: yes
      become: yes

    - name: update nginx config
      ansible.builtin.template:
        src: nginx/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes
    
    - name: create www directory
      ansible.builtin.file:
        path: "{{root_dir}}"
        state: directory
        mode: '0755'

    - name: create cowsay
      ansible.builtin.shell: "cowsay {{invite}}"
      register: invite_cowsay
      ignore_errors: yes

    - name: update index.html
      ansible.builtin.template:
        src: nginx/index3.html.j2
        dest: "{{root_dir}}/index.html"
      notify:
        - restart nginx
      become: yes

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
